"""Install / uninstall the Claude Code UserPromptSubmit hook for auto-injection.

Two pieces are written:

1. A shim script at ~/.claude-memory/hook/inject.sh that calls
   `claude-memory-inject`. The shim exists so the hook entry in
   settings.json is a stable absolute path; if the package is later
   uninstalled, the shim still exits 0 and Claude Code does not break.

2. A UserPromptSubmit entry in ~/.claude/settings.json pointing at the
   shim. settings.json is backed up with a timestamped suffix on every
   install run. The installer is idempotent — running twice will not
   create duplicate entries.

CLI:

    claude-memory-install-hook            # install
    claude-memory-install-hook --uninstall  # remove the entry (shim left in place)
    claude-memory-install-hook --print    # print what would be written, no changes
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime
from pathlib import Path


HOME = Path.home()
SHIM_DIR = HOME / ".claude-memory" / "hook"
SHIM_PATH = SHIM_DIR / "inject.sh"
SETTINGS_PATH = HOME / ".claude" / "settings.json"


def _shim_script(cli_path: str | None) -> str:
    """Generate the shim contents.

    If `cli_path` is given (the install-time absolute path of
    claude-memory-inject), bake it into the shim so Claude Code's
    subshell does not need to inherit the parent shell's PATH.
    Falls back to a PATH-based lookup if no path is provided.

    In all cases the shim exits 0 cleanly when the CLI cannot be
    found, so a stale hook never blocks a user prompt.
    """
    if cli_path:
        return (
            "#!/bin/sh\n"
            "# claude-memory auto-injection hook shim. "
            "Generated by claude-memory-install-hook.\n"
            "# Exits 0 if the CLI is missing so Claude Code never "
            "blocks on a stale hook.\n"
            f'CLI="{cli_path}"\n'
            '[ -x "$CLI" ] || exit 0\n'
            'exec "$CLI"\n'
        )
    return (
        "#!/bin/sh\n"
        "# claude-memory auto-injection hook shim. "
        "Generated by claude-memory-install-hook.\n"
        "command -v claude-memory-inject >/dev/null 2>&1 || exit 0\n"
        "exec claude-memory-inject\n"
    )


def _resolve_cli() -> str | None:
    """Return the absolute path of claude-memory-inject if discoverable."""
    found = shutil.which("claude-memory-inject")
    if found:
        return found
    # Fall back to looking in the same bin dir as the running interpreter.
    candidate = Path(sys.executable).parent / "claude-memory-inject"
    if candidate.exists() and candidate.is_file():
        return str(candidate)
    return None


def write_shim() -> Path:
    SHIM_DIR.mkdir(parents=True, exist_ok=True)
    cli_path = _resolve_cli()
    SHIM_PATH.write_text(_shim_script(cli_path), encoding="utf-8")
    SHIM_PATH.chmod(0o755)
    return SHIM_PATH


def _load_settings() -> dict:
    if not SETTINGS_PATH.exists():
        return {}
    try:
        return json.loads(SETTINGS_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(
            f"error: {SETTINGS_PATH} is not valid JSON ({exc}). "
            "Refusing to overwrite — fix it manually first."
        )


def _backup_settings() -> Path | None:
    if not SETTINGS_PATH.exists():
        return None
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup = SETTINGS_PATH.with_suffix(f".json.bak-{stamp}")
    shutil.copy2(SETTINGS_PATH, backup)
    return backup


def _hook_entry(command: str) -> dict:
    return {"hooks": [{"type": "command", "command": command}]}


def _has_our_entry(entries: list, command: str) -> bool:
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        for hook in entry.get("hooks", []) or []:
            if isinstance(hook, dict) and hook.get("command") == command:
                return True
    return False


def install(print_only: bool = False) -> None:
    shim_path = write_shim() if not print_only else SHIM_PATH
    command = str(shim_path)

    settings = _load_settings()
    hooks = settings.setdefault("hooks", {})
    ups = hooks.setdefault("UserPromptSubmit", [])
    if not isinstance(ups, list):
        raise SystemExit(
            f"error: settings.json hooks.UserPromptSubmit is not a list "
            f"(got {type(ups).__name__}). Refusing to overwrite — fix manually."
        )

    if _has_our_entry(ups, command):
        msg = f"already installed: {command}"
        if print_only:
            print(msg)
        else:
            print(msg)
            print(f"shim: {shim_path}")
            print(f"settings: {SETTINGS_PATH}")
        return

    ups.append(_hook_entry(command))

    if print_only:
        print("--- proposed settings.json ---")
        print(json.dumps(settings, indent=2))
        print("------------------------------")
        print(f"shim would be written to: {shim_path}")
        return

    backup = _backup_settings()
    SETTINGS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS_PATH.write_text(
        json.dumps(settings, indent=2) + "\n", encoding="utf-8"
    )
    print(f"installed UserPromptSubmit hook → {command}")
    if backup:
        print(f"backup: {backup}")
    print(f"shim:   {shim_path}")


def uninstall() -> None:
    if not SETTINGS_PATH.exists():
        print(f"no settings.json at {SETTINGS_PATH}, nothing to do")
        return

    settings = _load_settings()
    hooks = settings.get("hooks", {})
    ups = hooks.get("UserPromptSubmit", [])
    if not isinstance(ups, list):
        print("UserPromptSubmit is not a list, nothing to remove")
        return

    command = str(SHIM_PATH)
    new_ups = [
        entry for entry in ups
        if not (
            isinstance(entry, dict)
            and any(
                isinstance(h, dict) and h.get("command") == command
                for h in (entry.get("hooks") or [])
            )
        )
    ]

    if len(new_ups) == len(ups):
        print(f"no entry pointing at {command} — nothing to remove")
        return

    backup = _backup_settings()
    if new_ups:
        hooks["UserPromptSubmit"] = new_ups
    else:
        hooks.pop("UserPromptSubmit", None)
    if not hooks:
        settings.pop("hooks", None)

    SETTINGS_PATH.write_text(
        json.dumps(settings, indent=2) + "\n", encoding="utf-8"
    )
    print(f"removed UserPromptSubmit hook for {command}")
    if backup:
        print(f"backup: {backup}")
    print(f"shim left in place at: {SHIM_PATH}")
    print("(remove ~/.claude-memory/ if you also want to wipe audit logs)")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Install/uninstall the claude-memory UserPromptSubmit hook."
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove the hook entry (leaves the shim file in place).",
    )
    parser.add_argument(
        "--print",
        action="store_true",
        dest="print_only",
        help="Print what would be written, do not modify settings.json.",
    )
    args = parser.parse_args()

    if args.uninstall and args.print_only:
        print("--uninstall and --print are mutually exclusive", file=sys.stderr)
        return 2

    if args.uninstall:
        uninstall()
    else:
        install(print_only=args.print_only)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
